config/routes.rb
Rails.application.routes.draw do
  
   default_url_options :host => "example.com"
  
  
  resources :categories
  resources :orders do
   resources:orderitems
    end  
  
  
  devise_for :users do
      
      resources:orders
     end 

  get '/paid/:id' => 'static_pages#paid'
  
  get '/manager' => 'static_pages#adminsection'
  
  get '/checkout' => 'cart#createOrder'
  
  get '/done' => 'cart#done'
  
  get 'cart/index'

  resources :items
  #################################################
                                     root 'static_pages#home'

   get '/helppage' => 'static_pages#help'

  get '/aboutpage' => 'static_pages#about'

   get '/contact' => 'static_pages#contact'
   
   get '/menus' => 'items#index'


   get'/search' => 'items#search'
   post '/search' => 'items#search'
   
   get '/feedback' => 'static_pages#feedback'
 # get '/feedback' => 'static_pages#feedback'
get '/upgrade/:id' => 'static_pages#upgradeadmin'
get '/downgrade/:id' => 'static_pages#downgradeadmin'


get '/profile' => 'static_pages#profileuser'

get '/alluser' => 'static_pages#alluser'


  
  get '/log_in' => 'user#log_in'
  
  get '/log_out' => 'user#log_out'
 ################################ 
  get '/cart' => 'cart#index'
  
  get '/cart/:id' => 'cart#addtobasket'
  
  get '/clearcart' => 'cart#clearthecart'
  
  get '/remove/:id' => 'cart#deleteall'
  
  get '/decrease/:id' => 'cart#decreaseitems'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  
  
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
     @orders = Order.all
    
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
          
          
          
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  
  
    def search
    
   if params[:question].blank?  
    redirect_to(root_path, alert: "Empty field!") and return  
  else  
    
     st = "%#{params[:question]}%"
     
     @items = Item.where("title like ?", st)
  end
  
end
  
  
  
  def destroy
    
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="mainCont">


<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  
    
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :Ingredients %>
    <%= f.text_field :brand %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
   

 <div id="itemsContainer">
  
  <h1>menus </h1>
     
      <% @items.each do |item| %>
      
      
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm" ,size:"300*300"   ), item %>
       
        <p><%= item.description %></p>
       <p>Price <%= number_to_currency(item.price, :unit => "€") %>
       <br>
        Category: <%= item.category %>
        <br>
        
        <br>
         Ingredients: <%= item.brand %>
        <br>
       
        </p>
       
       
       
       <p>
        
        
      
            <% if current_user && current_user.admin? %>
       
         
         
         
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
         <% end %>
         
          <%= link_to 'Show',  item, :class => "button", :role => "button" %>
          <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
         
       </p>
       
       
        
      </div>
    <% end %>
      
</div>

<br>

<% if current_user && current_user.admin? %> 

<%= link_to 'New Item',  new_item_path, :class => "button", :role => "button" %>



<%= link_to 'New category',new_category_path, :class => "button", :role => "button" %>  

<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our dish  <%= @search_term %></h2>

<% if @items.length == 0  %>
<br />
<h2>No dish were found to match your search</h2>


<% end %>


    <table class="catalog">
  <% @items.each do |item| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
          </div>
          <div class="title">
            <%= link_to item.title, item %>
          </div>
          <div class="description">
            <%= item.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(item.price, :unit => "€") %>
          </div>
          
          <div class="links">
          <% if current_user && current_user.admin? %>
              <%= link_to 'Edit', edit_item_path(item) %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
            
              <a href="/cart/<%= item.id %>">Add to Cart</a>
            <%end%>  
        </div>
        </td>
      </tr>
    <% end %>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
   <%= link_to (image_tag @item.image_url, :class => "itemholsIm",size:"500*350"), @item %>
  
  
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @item.brand %>
</p>
<% if current_user && current_user.admin? %>
<%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>

<%= link_to 'Back', items_path %>